import json
import logging
from datetime import datetime

from agents import emit, get_genai_client

logger = logging.getLogger(__name__)
MODEL = "gemini-2.5-flash"
AGENT_NAME = "report_builder"


async def build_report(query: str, synthesis: dict, plan: dict, session_id: str, queue) -> dict:
    logger.info("[%s] build_report called | session_id=%s | query=%r", AGENT_NAME, session_id, query)

    await emit(queue, "agent_start", AGENT_NAME, "Generating final clinical brief...")

    client = get_genai_client()

    await emit(queue, "agent_thinking", AGENT_NAME,
               "Formatting report with citations and evidence grades...")

    prompt = f"""
    Generate a professional clinical research brief.

    Original question: {query}
    Synthesis data: {json.dumps(synthesis, indent=2)[:3000]}

    Create a complete clinical brief. Respond in JSON:
    {{
      "title": "Clinical Evidence Brief: [descriptive title]",
      "generated_at": "{datetime.utcnow().isoformat()}",
      "clinical_question": "{query}",
      "executive_summary": "...",
      "evidence_summary": {{
        "papers_reviewed": 0,
        "evidence_quality": "High|Moderate|Low",
        "date_range": "..."
      }},
      "risk_factors": [
        {{
          "factor": "...",
          "importance": "High|Medium|Low",
          "evidence_grade": "A|B|C",
          "recommendation": "..."
        }}
      ],
      "clinical_recommendations": [
        {{
          "priority": 1,
          "action": "...",
          "strength": "Strong|Conditional",
          "rationale": "..."
        }}
      ],
      "key_interventions": [...],
      "limitations": [...],
      "disclaimer": "This brief is generated by AI from public literature. Always verify with current clinical guidelines.",
      "markdown_report": "# Clinical Evidence Brief\\n\\n..."
    }}
    """

    logger.debug("[%s] Sending report prompt to Gemini (%d chars)", AGENT_NAME, len(prompt))
    response = client.models.generate_content(model=MODEL, contents=prompt)
    text = response.text.strip().strip("```json").strip("```").strip()
    logger.debug("[%s] Gemini raw response (%d chars):\n%s", AGENT_NAME, len(text), text[:400])

    try:
        report = json.loads(text)
        logger.info("[%s] Report parsed | title=%r | risk_factors=%d | recommendations=%d",
                    AGENT_NAME,
                    report.get("title"),
                    len(report.get("risk_factors", [])),
                    len(report.get("clinical_recommendations", [])))
    except Exception as e:
        logger.error("[%s] JSON parse failed: %s — using fallback report", AGENT_NAME, e)
        report = {
            "title": "Clinical Evidence Brief",
            "generated_at": datetime.utcnow().isoformat(),
            "clinical_question": query,
            "executive_summary": str(synthesis.get("executive_summary", "")),
            "evidence_summary": {"evidence_quality": synthesis.get("evidence_quality", "Low"),
                                  "papers_reviewed": 0},
            "risk_factors": [],
            "clinical_recommendations": synthesis.get("recommendations", []),
            "key_interventions": [],
            "limitations": synthesis.get("limitations", []),
            "disclaimer": "AI-generated. Verify with clinical guidelines.",
            "markdown_report": f"# Clinical Brief\n\n{str(synthesis)[:1000]}",
        }

    await emit(queue, "agent_done", AGENT_NAME,
               "Clinical brief generated and ready",
               {"title": report.get("title"),
                "recommendations_count": len(report.get("clinical_recommendations", []))})

    logger.info("[%s] Done | session_id=%s", AGENT_NAME, session_id)
    return report
