import json
from datetime import datetime

from agents import emit, get_genai_client

MODEL = "gemini-2.0-flash"
AGENT_NAME = "report_builder"


async def build_report(query: str, synthesis: dict, plan: dict, session_id: str, queue) -> dict:
    await emit(queue, "agent_start", AGENT_NAME, "Generating final clinical brief...")

    client = get_genai_client()

    await emit(queue, "agent_thinking", AGENT_NAME,
               "Formatting report with citations and evidence grades...")

    prompt = f"""
    Generate a professional clinical research brief.

    Original question: {query}
    Synthesis data: {json.dumps(synthesis, indent=2)[:3000]}

    Create a complete clinical brief. Respond in JSON:
    {{
      "title": "Clinical Evidence Brief: [descriptive title]",
      "generated_at": "{datetime.utcnow().isoformat()}",
      "clinical_question": "{query}",
      "executive_summary": "...",
      "evidence_summary": {{
        "papers_reviewed": 0,
        "evidence_quality": "High|Moderate|Low",
        "date_range": "..."
      }},
      "risk_factors": [
        {{
          "factor": "...",
          "importance": "High|Medium|Low",
          "evidence_grade": "A|B|C",
          "recommendation": "..."
        }}
      ],
      "clinical_recommendations": [
        {{
          "priority": 1,
          "action": "...",
          "strength": "Strong|Conditional",
          "rationale": "..."
        }}
      ],
      "key_interventions": [...],
      "limitations": [...],
      "disclaimer": "This brief is generated by AI from public literature. Always verify with current clinical guidelines.",
      "markdown_report": "# Clinical Evidence Brief\\n\\n..."
    }}
    """

    response = client.models.generate_content(model=MODEL, contents=prompt)
    text = response.text.strip().strip("```json").strip("```").strip()

    try:
        report = json.loads(text)
    except Exception:
        report = {
            "title": "Clinical Evidence Brief",
            "generated_at": datetime.utcnow().isoformat(),
            "clinical_question": query,
            "executive_summary": str(synthesis.get("executive_summary", "")),
            "evidence_summary": {"evidence_quality": synthesis.get("evidence_quality", "Low"),
                                  "papers_reviewed": 0},
            "risk_factors": [],
            "clinical_recommendations": synthesis.get("recommendations", []),
            "key_interventions": [],
            "limitations": synthesis.get("limitations", []),
            "disclaimer": "AI-generated. Verify with clinical guidelines.",
            "markdown_report": f"# Clinical Brief\n\n{str(synthesis)[:1000]}"
        }

    await emit(queue, "agent_done", AGENT_NAME,
               "Clinical brief generated and ready",
               {"title": report.get("title"),
                "recommendations_count": len(report.get("clinical_recommendations", []))})

    return report
